name: deploy-prod

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Set environment variables
        run: |
          touch .env.local
          echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}" >> .env.local

      - name: Build & Export
        run: |
          yarn install
          yarn build

      - name: Deploy to S3 and Invalidate Cloudfront in prod mode
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
        run: |
          aws s3 sync ./dist s3://wafflestudio-22.5-prod --delete
          aws cloudfront create-invalidation --distribution-id ENNREX04O38RJ --paths "/*"
